version: '2'

services:
  mongodb:
    image: 'bitnami/mongodb:4.0'
    ports:
      - "27017:27017"
    volumes:
      - '/Users/usuario/Desktop/JuegoDeVida/mongo:/bitnami'
volumes:
  mongodb_data:
    driver: local
